site_name: Gandi Cookbook
site_description: Unofficial, experimental community documentation. Yay!

display_github: True
github_user: soulshake
github_repo: Gandi-cookbook
repo_url: https://github.com/soulshake/Gandi-cookbook
